#!/usr/bin/python
#
# Copyright (c) 2009.
#
# DMI
# Lyngbyvej 100
# DK-2100 Copenhagen
# Denmark
#
# Author(s): 
#   Lars Orum Rasmussen
#   Martin Raspaud

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
import sys
import logging
import getopt
from datetime import datetime

from datex.rpcproxy import RPCProxy
from datex import datex_config

logger = logging.getLogger('datex-client')

# time.strptime not thread-safe (Issue 7980), work around
datetime.strptime("1956", "%Y")

#-----------------------------------------------------------------------------
#
# Handle options
#
#-----------------------------------------------------------------------------
def usage():
    print >>sys.stderr, """datex_cmd [-c] [-H] <command> [-n<client-name>] [<datatype>] [<filename>]
    -c, md5 check of received file (together with <get_file>)
    -n <client-name>, section name of client in config file
    -H, this info"""
    cmds = sorted([x for x in dir(RPCProxy) if x[0] != '_' and callable(getattr(RPCProxy, x))])
    print "    valid commands: %s"%' '.join(cmds)
    sys.exit(2)

kargs = {}
datatype = ''
client_name = 'client'
opts,args = getopt.getopt( sys.argv[1:], 'Hcn:' )
for k,v in opts:
    if k == '-H': 
        usage()
    elif k == '-n':
        client_name = v
    elif k == '-c': 
        kargs['check_md5'] = True
try:
    cmd = args.pop(0)
except IndexError:
    usage()

if kargs.get('check_md5', None) and cmd != 'get_file':
    print >>sys.stderr, "Invalid option '-c', only valid for command 'get_file'"
    sys.exit(2)

# A single RPC call.
server = RPCProxy("http://%s:%d"%datex_config.get_client(name=client_name)[0])
print 'server', server.url

ret = getattr(server, cmd)(*args, **kargs)
if not isinstance(ret, (list, tuple)):
    ret = (ret,)
for r in ret:
    if r:
        print r
